### ISSUE TITLE
A Complete Guide to Grid | CSS-Tricks

### ISSUE THREAD

**Issue by zhuangyin8** [zhuangyin8/zhuangyin8.github.io#4]
---
layout: post
title: A Complete Guide to Grid
date: SEPTEMBER 13, 2017
categories: CSS Grid
---
# A Complete Guide to Grid

- [Introduction](#introduction)
- [Basics and Browser Support](#basics-and-browser-support)
- [Important Terminology](#important-terminology)
- [Grid Properties Table of Contents](#grid-properties-table-of-contents)

[@A Complete Guide to Grid | CSS-Tricks](https://css-tricks.com/snippets/css/complete-guide-grid/)

CSS Grid Layout is the most powerful layout system available in CSS. It is a 2-dimensional system, meaning it can handle both columns and rows, unlike [flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) which is largely a 1-dimensional system. You work with Grid Layout by applying CSS rules both to a parent element (which becomes the Grid Container) and to that elements children (which become Grid Items).

This article was ported over from [Chris House's guide](http://chris.house/blog/a-complete-guide-css-grid-layout/), by Chris himself, who is keeping both up-to-date.

## Introduction

CSS Grid Layout (aka "Grid"), is a two-dimensional grid-based layout system that aims to do nothing less than completely change the way we design grid-based user interfaces. CSS has always been used to lay out our web pages, but it's never done a very good job of it. First we used tables, then floats, positioning and inline-block, but all of these methods were essentially hacks and left out a lot of important functionality (vertical centering, for instance). Flexbox helped out, but it's intended for simpler one-dimensional layouts, not complex two-dimensional ones (Flexbox and Grid actually work very well together). **Grid is the very first CSS module created specifically to solve the layout problems we've all been hacking our way around for as long as we've been making websites**.

There are two primary things that inspired me to create this guide. The first is Rachel Andrew's awesome book [Get Ready for CSS Grid Layout.](https://abookapart.com/products/get-ready-for-css-grid-layout) It's a thorough, clear introduction to Grid and is the basis of this entire article. I _highly_ encourage you to buy it and read it. My other big inspiration is Chris Coyier's [A Complete Guide to Flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/), which has been my go-to resource for everything flexbox. It's helped a ton of people, evident by the fact that it's the top result when you Google "flexbox." You'll notice many similarities between his post and mine, because why not steal from the best?

✔ My intention with this guide is to present the Grid concepts as they exist in the very latest version of the specification. So I won't be covering the out of date IE syntax, and I'll do my best to update this guide regularly as the spec matures.

## Basics and Browser Support

To get started you have to define a container element as a grid with `[display: grid](#prop-display)`, set the column and row sizes with `grid-template-columns` and `grid-template-rows`, and then place its child elements into the grid with `[grid-column](#prop-grid-column-row)` and `[grid-row](#prop-grid-column-row)`. Similarly to flexbox, the source order of the grid items doesn't matter. Your CSS can place them in any order, which makes it super easy to rearrange your grid with media queries. Imagine defining the layout of your entire page, and then completely rearranging it to accommodate a different screen width all with only a couple lines of CSS. Grid is one of the most powerful CSS modules ever introduced.

As of March 2017, many browsers shipped native, unprefixed support for CSS Grid: Chrome (including on Android), Firefox, Safari (including on iOS), and Opera. Internet Explorer 10 and 11 on the other hand support it, but it's an old implementation with an outdated syntax. Edge support has been announced, but it's not here yet.

This browser support data is from [Caniuse](http://caniuse.com/#feat=css-grid), which has more detail. A number indicates that browser supports the feature at that version and up.

### Desktop

| Chrome | Opera | Firefox | IE   | Edge | Safari |
| ------ | ----- | ------- | ---- | ---- | ------ |
| 57     | 44    | 52      | 11* | 16   | 10.1   |

### Mobile / Tablet

| iOS Safari | Opera Mobile    | Opera Mini    | Android | Android Chrome | Android Firefox |
| ---------- | --------------- | ------------- | ------- | -------------- | --------------- |
| 10.3       | NoNot supported | Not supported | 56      | 61             | 55              |

Aside from Microsoft, browser manufacturers appear to be holding off on letting Grid loose in the wild until the spec is fully cooked. This is a good thing, as it means we won't have to worry about learning multiple syntaxes.

It's only a matter of time before you can use Grid in production. But the time to learn it is now.

## Important Terminology

Before diving into the concepts of Grid it's important to understand the terminology. Since the terms involved here are all kinda conceptually similar, it's easy to confuse them with one another if you don't first memorize their meanings defined by the Grid specification. But don't worry, there aren't many of them.

### Grid Container

The element on which `display: grid` is applied. It's the direct parent of all the grid items. In this example `container` is the grid container.

> ### 网格容器
>
> 网格容器是指这个元素使用了display: grid，它是所有网格元素的直接父级，在这个例子container的元素就是网格容器。

```html
<div class="container">
    <div class="item item-1"></div>
    <div class="item item-2"></div>
    <div class="item item-3"></div>
</div>
```

### Grid Item

The children (e.g. _direct_ descendants) of the grid container. Here the `item` elements are grid items, but `sub-item` isn't.

> ### 网格子项
>
> 网格子项是指网格容器的子元素（比如其直接后代），在下面的例子中item的元素是网格子项，但sub-item的元素不是。

```html
<div class="container">
    <div class="item"></div>
    <div class="item">
        <p class="sub-item"></p>
    </div>
    <div class="item"></div>
</div>
```

#### Grid Line

The dividing lines that make up the structure of the grid. They can be either vertical ("column grid lines") or horizontal ("row grid lines") and reside on either side of a row or column. Here the yellow line is an example of a column grid line.

> ### 网格线
>
> 分隔的线组成了网格的结构。它们可以是垂直的（“列网格线”）或者水平的（“行网格线”），也可以在行或列的任一边。下面的例子中黄色的线是一个列网格线的例子。

![Grid line](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-line.png)

#### Grid Track

The space between two adjacent grid lines. You can think of them like the columns or rows of the grid. Here's the grid track between the second and third row grid lines.

> ### 网格轨迹
>
> 网格轨迹是指两根毗邻线中间的位置，你可以认为是网格的行或者列，下面例子的中网格轨迹是第二和第三行网格线中间的位置。

![Grid track](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-track.png)

#### Grid Cell

The space between two adjacent row and two adjacent column grid lines. It's a single "unit" of the grid. Here's the grid cell between row grid lines 1 and 2, and column grid lines 2 and 3.

> ### 网格单元
>
> 网格单元是指两根毗邻的行网格线和列网格线中间的位置，它是一个单独的网格“单元”，下面的例子中网格单元是指第 1 和 2 根行网格线和第 2 和 3 根列网格线中间的位置。

![Grid cell](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-cell.png)

#### Grid Area

The total space surrounded by four grid lines. A grid area may be comprised of any number of grid cells. Here's the grid area between row grid lines 1 and 3, and column grid lines 1 and 3.

> ### 网格区域
>
> 网格区域是指 4 根网格线包围的空间，一个网格空间可能由任意数量的网格单元构成。下面的例子中网格区域是指在第 1 和 3 的行网格线和第 1 和 3 列网格线中间的位置。

![Grid area](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-area.png)

### Properties for the Grid Container

- [display](#prop-display)
- [grid-template-columns](#prop-grid-template-columns-rows)
- [grid-template-rows](#prop-grid-template-columns-rows)
- [grid-template-areas](#prop-grid-template-areas)
- [grid-template](#prop-grid-template)
- [grid-column-gap](#prop-grid-clumns-gap)
- [grid-row-gap](#prop-grid-row-gap)
- [grid-gap](#prop-grid-gap)
- [justify-items](#prop-justify-items)
- [align-items](#prop-align-content)
- [justify-content](#prop-justify-content)
- [align-content](#prop-align-content)
- [grid-auto-columns](#prop-grid-auto-columns)
- [grid-auto-rows](#prop-grid-auto-rows)
- [grid-auto-flow](#prop-grid-auto-folw)
- [grid](#prop-grid)

### Properties for the Grid Items

- [grid-column-start](#prop-grid-column-row-start-end)
- [grid-column-end](#prop-grid-column-row-start-end)
- [grid-row-start](#prop-grid-column-row-start-end)
- [grid-row-end](#prop-grid-column-row-start-end)
- [grid-column](#prop-grid-column-row)
- [grid-row](#prop-grid-column-row)
- [grid-area](#prop-grid-area)
- [justify-self](#prop-justify-self)
- [align-self](#prop-align-self)

### Properties for the Parent

(Grid Container)

<div id="prop-display">

#### display

Defines the element as a grid container and establishes a new _grid formatting context_ for its contents.

Values:

- **grid** - generates a block-level grid
- **inline-grid** - generates an inline-level grid
- **subgrid** - if your grid container is itself a grid item (i.e. nested grids), you can use this property to indicate that you want the sizes of its rows/columns to be taken from its parent rather than specifying its own.

```css
.container {
    display: grid | inline-grid | subgrid;
}
```

Note: `column`, `float`, `clear`, and `vertical-align` have no effect on a grid container.

</div>

<div id="prop-grid-template-columns-rows">

#### grid-template-columns grid-template-rows

Defines the columns and rows of the grid with a space-separated list of values. The values represent the track size, and the space between them represents the grid line.

Values:

- **`<track-size>`** - can be a length, a percentage, or a fraction of the free space in the grid (using the `fr` unit)
- **`<line-name>`** - an arbitrary name of your choosing

```css
.container {
    grid-template-columns: <track-size> ... | <line-name> <track-size> ...;
    grid-template-rows: <track-size> ... | <line-name> <track-size> ...;
}
```

Examples:

When you leave an empty space between the track values, the grid lines are automatically assigned numerical names:

```css
.container{
    grid-template-columns: 40px 50px auto 50px 40px;
    grid-template-rows: 25% 100px auto;
}
```

![Grid with auto named lines](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-numbers.png)

But you can choose to explicitly name the lines. Note the bracket syntax for the line names:

```css
.container {
    grid-template-columns: [first] 40px [line2] 50px [line3] auto [col4-start] 50px [five] 40px [end];
    grid-template-rows: [row1-start] 25% [row1-end] 100px [third-line] auto [last-line];
}
```

![Grid with user named lines](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-names.png)

Note that a line can have more than one name. For example, here the second line will have two names: row1-end and row2-start:

```css
.container{
    grid-template-rows: [row1-start] 25% [row1-end row2-start] 25% [row2-end];
}
```

If your definition contains repeating parts, you can use the `repeat()` notation to streamline things:

```css
.container {
    grid-template-columns: repeat(3, 20px [col-start]) 5%;
}
```

Which is equivalent to this:

```css
.container {
    grid-template-columns: 20px [col-start] 20px [col-start] 20px [col-start] 5%;
}
```

The `fr` unit allows you to set the size of a track as a fraction of the free space of the grid container. For example, this will set each item to one third the width of the grid container:

```css
    .container {
      grid-template-columns: 1fr 1fr 1fr;
    }
```

The free space is calculated _after_ any non-flexible items. In this example the total amount of free space available to the `fr` units doesn't include the 50px:

```css
    .container {
      grid-template-columns: 1fr 50px 1fr 1fr;
    }
```

</div>

<div id="prop-grid-template-areas">

#### grid-template-areas

Defines a grid template by referencing the names of the grid areas which are specified with the `grid-areas` property. Repeating the name of a grid area causes the content to span those cells. A period signifies an empty cell. The syntax itself provides a visualization of the structure of the grid.

Values:

- **`<grid-area-name>`** - the name of a grid area specified with `grid-areas`
- **`.`** - a period signifies an empty grid cell
- **`none`** - no grid areas are defined

```css
.container {
    grid-template-areas:
    "<grid-area-name> | . | none | ..."
    "...";
}
```

Example:

```css
.item-a {
    grid-area: header;
}
.item-b {
    grid-area: main;
}
.item-c {
    grid-area: sidebar;
}
.item-d {
    grid-area: footer;
}

.container {
    grid-template-columns: 50px 50px 50px 50px;
    grid-template-rows: auto;
    grid-template-areas:
    "header header header header"
    "main main . sidebar"
    "footer footer footer footer";
}
```

That'll create a grid that's four columns wide by three rows tall. The entire top row will be comprised of the **header** area. The middle row will be comprised of two **main** areas, one empty cell, and one **sidebar** area. The last row is all **footer**.

![Example of grid-template-areas](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-template-areas.png)

Each row in your declaration needs to have the same number of cells.

You can use any number of adjacent periods to declare a single empty cell. As long as the periods have no spaces between them they represent a single cell.

Notice that you're not naming lines with this syntax, just areas. When you use this syntax the lines on either end of the areas are actually getting named automatically. If the name of your grid area is **_foo_**, the name of the area's starting row line and starting column line will be **_foo_-start**, and the name of its last row line and last column line will be **_foo_-end**. This means that some lines might have multiple names, such as the far left line in the above example, which will have three names: header-start, main-start, and footer-start.

</div>

<div id="prop-grid-template">

#### grid-template

A shorthand for setting `grid-template-rows`, `grid-template-columns`, and `grid-template-areas` in a single declaration.

Values:

- **none** - sets all three properties to their initial values
- **subgrid** - sets `grid-template-rows` and `grid-template-columns` to `subgrid`, and `grid-template-areas` to its initial value
- **`<grid-template-rows>` / `<grid-template-columns>`** - sets `grid-template-columns` and `grid-template-rows` to the specified values, respectively, and sets `grid-template-areas` to `none`

```css
.container {
    grid-template: none | subgrid | <grid-template-rows> / <grid-template-columns>;
}
```

It also accepts a more complex but quite handy syntax for specifying all three. Here's an example:

```css
.container {
    grid-template:
    [row1-start] "header header header" 25px [row1-end]
    [row2-start] "footer footer footer" 25px [row2-end]
    / auto 50px auto;
}
```

That's equivalent to this:

```css
.container {
    grid-template-rows: [row1-start] 25px [row1-end row2-start] 25px [row2-end];
    grid-template-columns: auto 50px auto;
    grid-template-areas:
    "header header header"
    "footer footer footer";
}
```

Since `grid-template` doesn't reset the _implicit_ grid properties (`grid-auto-columns`, `grid-auto-rows`, and `grid-auto-flow`), which is probably what you want to do in most cases, it's recommended to use the `grid` property instead of `grid-template`.

</div>

<div id="prop-grid-column-row-gap">

#### grid-column-gap

grid-row-gap

Specifies the size of the grid lines. You can think of it like setting the width of the gutters between the columns/rows.

Values:

- **`<line-size>`** - a length value

```css
.container {
    grid-column-gap: <line-size>;
    grid-row-gap: <line-size>;
}
```

Example:

```css
.container {
    grid-template-columns: 100px 50px 100px;
    grid-template-rows: 80px auto 80px;
    grid-column-gap: 10px;
    grid-row-gap: 15px;
}
```

![Example of grid-column-gap and grid-row-gap](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-column-row-gap.png)

The gutters are only created _between_ the columns/rows, not on the outer edges.

</div>

<div id="prop-grid-gap">

#### grid-gap

A shorthand for `grid-row-gap` and `grid-column-gap`

Values:

- **`<grid-row-gap>` `<grid-column-gap>`** - length values

```css
.container {
    grid-gap: <grid-row-gap> <grid-column-gap>;
}
```

Example:

```css
.container{
    grid-template-columns: 100px 50px 100px;
    grid-template-rows: 80px auto 80px;
    grid-gap: 10px 15px;
}
```

If no `grid-row-gap` is specified, it's set to the same value as `grid-column-gap`

</div>

<div id="prop-justify-items">

#### justify-items

Aligns the content inside a grid item along the _row_ axis (as opposed to `align-items` which aligns along the _column_ axis). This value applies to all grid items inside the container.

Values:

- **start** - aligns the content to the left end of the grid area
- **end** - aligns the content to the right end of the grid area
- **center** - aligns the content in the center of the grid area
- **stretch** - fills the whole width of the grid area (this is the default)

```css
.container {
    justify-items: start | end | center | stretch;
}
```

Examples:

```css
.container {
    justify-items: start;
}
```

![Example of justify-items set to start](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-justify-items-start.png)

```css
.container{
    justify-items: end;
}
```

![Example of justify-items set to end](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-justify-items-end.png)

```css
.container{
    justify-items: center;
}
```

![Example of justify-items set to center](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-justify-items-center.png)

```css
.container{
    justify-items: stretch;
}
```

![Example of justify-items set to stretch](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-justify-items-stretch.png)

This behavior can also be set on individual grid items via the `justify-self` property.

</div>

<div id="prop-align-items">

#### align-items

Aligns the content inside a grid item along the _column_ axis (as opposed to `justify-items` which aligns along the _row_ axis). This value applies to all grid items inside the container.

Values:

- **start** - aligns the content to the top of the grid area
- **end** - aligns the content to the bottom of the grid area
- **center** - aligns the content in the center of the grid area
- **stretch** - fills the whole height of the grid area (this is the default)

```css
.container {
    align-items: start | end | center | stretch;
}
```

Examples:

```css
.container {
    align-items: start;
}
```

![Example of align-items set to start](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-align-items-start.png)

```css
.container {
    align-items: end;
}
```

![Example of align-items set to end](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-align-items-end.png)

```css
.container {
    align-items: center;
}
```

![Example of align-items set to center](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-align-items-center.png)

```css
.container {
    align-items: stretch;
}
```

![Example of align-items set to stretch](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-align-items-stretch.png)

This behavior can also be set on individual grid items via the `[align-self](#prop-align-self)` property.

</div>

<div id="prop-justify-content">

#### justify-content

Sometimes the total size of your grid might be less than the size of its grid container. This could happen if all of your grid items are sized with non-flexible units like `px`. In this case you can set the alignment of the grid within the grid container. This property aligns the grid along the _row_ axis (as opposed to `align-content` which aligns the grid along the _column_ axis).

Values:

- **start** - aligns the grid to the left end of the grid container
- **end** - aligns the grid to the right end of the grid container
- **center** - aligns the grid in the center of the grid container
- **stretch** - resizes the grid items to allow the grid to fill the full width of the grid container
- **space-around** - places an even amount of space between each grid item, with half-sized spaces on the far ends
- **space-between** - places an even amount of space between each grid item, with no space at the far ends
- **space-evenly** - places an even amount of space between each grid item, including the far ends

```css
.container {
    justify-content: start | end | center | stretch | space-around | space-between | space-evenly;
}
```

Examples:

```css
.container {
    justify-content: start;
}
```

![Example of justify-content set to start](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-justify-content-start.png)

```css
.container {
    justify-content: end;
}
```

![Example of justify-content set to end](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-justify-content-end.png)

```css
.container {
    justify-content: center;
}
```

![Example of justify-content set to center](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-justify-content-center.png)

```css
.container {
    justify-content: stretch;
}
```

![Example of justify-content set to stretch](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-justify-content-stretch.png)

```css
.container {
    justify-content: space-around;
}
```

![Example of justify-content set to space-around](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-justify-content-space-around.png)

```css
.container {
    justify-content: space-between;
}
```

![Example of justify-content set to space-between](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-justify-content-space-between.png)

```css
.container {
    justify-content: space-evenly;
}
```

![Example of justify-content set to space-evenly](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-justify-content-space-evenly.png)

</div>

<div id="prop-align-content">

#### align-content

Sometimes the total size of your grid might be less than the size of its grid container. This could happen if all of your grid items are sized with non-flexible units like `px`. In this case you can set the alignment of the grid within the grid container. This property aligns the grid along the _column_ axis (as opposed to `[justify-content](#prop-justify-content)` which aligns the grid along the _row_ axis).

Values:

- **start** - aligns the grid to the top of the grid container
- **end** - aligns the grid to the bottom of the grid container
- **center** - aligns the grid in the center of the grid container
- **stretch** - resizes the grid items to allow the grid to fill the full height of the grid container
- **space-around** - places an even amount of space between each grid item, with half-sized spaces on the far ends
- **space-between** - places an even amount of space between each grid item, with no space at the far ends
- **space-evenly** - places an even amount of space between each grid item, including the far ends

```css
.container {
    align-content: start | end | center | stretch | space-around | space-between | space-evenly;
}
```

Examples:

```css
.container {
    align-content: start;
}
```

![Example of align-content set to start](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-align-content-start.png)

```css
.container {
    align-content: end;
}
```

![Example of align-content set to end](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-align-content-end.png)

```css
.container {
    align-content: center;
}
```

![Example of align-content set to center](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-align-content-center.png)

```css
.container {
    align-content: stretch;
}
```

![Example of align-content set to stretch](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-align-content-stretch.png)

```css
.container {
    align-content: space-around;
}
```

![Example of align-content set to space-around](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-align-content-space-around.png)

```css
.container {
    align-content: space-between;
}
```

![Example of align-content set to space-between](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-align-content-space-between.png)

```css
.container {
    align-content: space-evenly;
}
```

![Example of align-content set to space-evenly](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-align-content-space-evenly.png)

</div>

<div id="prop-grid-auto-columns-rows">

#### grid-auto-columns

grid-auto-rows

Specifies the size of any auto-generated grid tracks (aka _implicit grid tracks_). Implicit grid tracks get created when you explicitly position rows or columns (via `grid-template-rows`/`grid-template-columns`) that are out of range of the defined grid.

Values:

- **`<track-size>`** - can be a length, a percentage, or a fraction of the free space in the grid (using the `fr` unit)

```css
.container {
    grid-auto-columns: <track-size> ...;
    grid-auto-rows: <track-size> ...;
}
```

To illustrate how implicit grid tracks get created, think about this:

```css
.container {
    grid-template-columns: 60px 60px;
    grid-template-rows: 90px 90px
}
```

![Example of 2 x 2 grid](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-auto.png)

This creates a 2 x 2 grid.

But now imagine you use `grid-column` and `grid-row` to position your grid items like this:

```css
.item-a {
    grid-column: 1 / 2;
    grid-row: 2 / 3;
}
.item-b {
    grid-column: 5 / 6;
    grid-row: 2 / 3;
}
```

![Example of implicit tracks](https://cdn.css-tricks.com/wp-content/uploads/2016/03/implicit-tracks.png)

We told .item-b to start on column line 5 and end at column line 6, _but we never defined a column line 5 or 6_. Because we referenced lines that don't exist, implicit tracks with widths of 0 are created to fill in the gaps. We can use `grid-auto-columns` and `grid-auto-rows` to specify the widths of these implicit tracks:

```css
.container {
    grid-auto-columns: 60px;
}
```

![Example of implicit tracks](https://cdn.css-tricks.com/wp-content/uploads/2016/03/implicit-tracks-with-widths.png)

</div>

<div id="prop-grid-auto-flow">

#### grid-auto-flow

If you have grid items that you don't explicitly place on the grid, the _auto-placement algorithm_ kicks in to automatically place the items. This property controls how the auto-placement algorithm works.

Values:

- **row** - tells the auto-placement algorithm to fill in each row in turn, adding new rows as necessary
- **column** - tells the auto-placement algorithm to fill in each column in turn, adding new columns as necessary
- **dense** - tells the auto-placement algorithm to attempt to fill in holes earlier in the grid if smaller items come up later

```css
.container {
    grid-auto-flow: row | column | row dense | column dense
}
```

Note that **dense** might cause your items to appear out of order.

Examples:

Consider this HTML:

```html
<section class="container">
    <div class="item-a">item-a</div>
    <div class="item-b">item-b</div>
    <div class="item-c">item-c</div>
    <div class="item-d">item-d</div>
    <div class="item-e">item-e</div>
</section>
```

You define a grid with five columns and two rows, and set `grid-auto-flow` to `row` (which is also the default):

```css
.container {
    display: grid;
    grid-template-columns: 60px 60px 60px 60px 60px;
    grid-template-rows: 30px 30px;
    grid-auto-flow: row;
}
```

When placing the items on the grid, you only specify spots for two of them:

```css
.item-a {
    grid-column: 1;
    grid-row: 1 / 3;
}
.item-e {
    grid-column: 5;
    grid-row: 1 / 3;
}
```

Because we set `grid-auto-flow` to `row`, our grid will look like this. Notice how the three items we didn't place (**item-b**, **item-c** and **item-d**) flow across the available rows:

![Example of grid-auto-flow set to row](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-auto-flow-row.png)

If we instead set `grid-auto-flow` to `column`, **item-b**, **item-c** and **item-d** flow down the columns:

```css
.container {
    display: grid;
    grid-template-columns: 60px 60px 60px 60px 60px;
    grid-template-rows: 30px 30px;
    grid-auto-flow: column;
}
```

![Example of grid-auto-flow set to column](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-auto-flow-column.png)

</div>

<div id="prop-grid">

#### grid

A shorthand for setting all of the following properties in a single declaration: `grid-template-rows`, `grid-template-columns`, `grid-template-areas`, `grid-auto-rows`, `grid-auto-columns`, and `grid-auto-flow`. It also sets `grid-column-gap` and `grid-row-gap` to their initial values, even though they can't be explicitly set by this property.

Values:

- **none** - sets all sub-properties to their initial values
- **`<grid-template-rows>` / `<grid-template-columns>`** - sets `grid-template-rows` and `grid-template-columns` to the specified values, respectively, and all other sub-properties to their initial values
- **`<grid-auto-flow>` \[`<grid-auto-rows>` [ / `<grid-auto-columns>`] ]** - accepts all the same values as `grid-auto-flow`, `grid-auto-rows` and `grid-auto-columns`, respectively. If `grid-auto-columns` is omitted, it is set to the value specified for `grid-auto-rows`. If both are omitted, they are set to their initial values

```css
.container {
    grid: none | <grid-template-rows> / <grid-template-columns> | <grid-auto-flow> [<grid-auto-rows> [/ <grid-auto-columns>]];
}
```

Examples:

The following two code blocks are equivalent:

```css
.container {
    grid: 200px auto / 1fr auto 1fr;
}
```

```css
.container {
    grid-template-rows: 200px auto;
    grid-template-columns: 1fr auto 1fr;
    grid-template-areas: none;
}
```

And the following two code blocks are equivalent:

```css
.container {
    grid: column 1fr / auto;
}
```

```css
.container {
    grid-auto-flow: column;
    grid-auto-rows: 1fr;
    grid-auto-columns: auto;
}
```

</div>

It also accepts a more complex but quite handy syntax for setting everything at once. You specify `grid-template-areas`, `grid-template-rows` and `grid-template-columns`, and all the other sub-properties are set to their initial values. What you're doing is specifying the line names and track sizes inline with their respective grid areas. This is easiest to describe with an example:

```css
.container {
    grid: [row1-start] "header header header" 1fr [row1-end]
        [row2-start] "footer footer footer" 25px [row2-end]
        / auto 50px auto;
}
```

That's equivalent to this:

```css
.container {
    grid-template-areas:
    "header header header"
    "footer footer footer";
    grid-template-rows: [row1-start] 1fr [row1-end row2-start] 25px [row2-end];
    grid-template-columns: auto 50px auto;
}
```

</div>

<div class="flex-half flex-child">

## Properties for the Children

<span>(Grid Items)</span>

<div id="prop-grid-column-row-start-end">

#### grid-column-start

grid-column-end
grid-row-start
grid-row-end

Determines a grid item's location within the grid by referring to specific grid lines. `grid-column-start`/`grid-row-start` is the line where the item begins, and `grid-column-end`/`grid-row-end` is the line where the item ends.

Values:

- **`<line>`** - can be a number to refer to a numbered grid line, or a name to refer to a named grid line
- **span `<number>`** - the item will span across the provided number of grid tracks
- **span `<name>`** - the item will span across until it hits the next line with the provided name
- **auto** - indicates auto-placement, an automatic span, or a default span of one

```css
.item {
    grid-column-start: <number> | <name> | span <number> | span <name> | auto
    grid-column-end: <number> | <name> | span <number> | span <name> | auto
    grid-row-start: <number> | <name> | span <number> | span <name> | auto
    grid-row-end: <number> | <name> | span <number> | span <name> | auto
}
```

Examples:

```css
.item-a {
    grid-column-start: 2;
    grid-column-end: five;
    grid-row-start: row1-start
    grid-row-end: 3
}
```

![Example of grid-row/column-start/end](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-start-end-a.png)

```css
.item-b {
    grid-column-start: 1;
    grid-column-end: span col4-start;
    grid-row-start: 2
    grid-row-end: span 2
}
```

![Example of grid-row/column-start/end](https://cdn.css-tricks.com/wp-content/uploads/2016/11/grid-start-end-b.png)

If no `grid-column-end`/`grid-row-end` is declared, the item will span 1 track by default.

Items can overlap each other. You can use `z-index` to control their stacking order.

</div>

<div id="prop-grid-column-row">

#### grid-column

grid-row

Shorthand for `[grid-column-start](#prop-grid-column-row-start-end)` + `[grid-column-end](#prop-grid-column-row-start-end)`, and `[grid-row-start](#prop-grid-column-row-start-end)` + `[grid-row-end](#prop-grid-column-row-start-end)`, respectively.

Values:

-   **`<start-line>` / `<end-line>`** - each one accepts all the same values as the longhand version, including span

```css
.item {
    grid-column: <start-line> / <end-line> | <start-line> / span <value>;
    grid-row: <start-line> / <end-line> | <start-line> / span <value>;
}
```

Example:

```css
.item-c {
    grid-column: 3 / span 2;
    grid-row: third-line / 4;
}
```

![Example of grid-column/grid-row](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-start-end-c.png)

If no end line value is declared, the item will span 1 track by default.

</div>

<div id="prop-grid-area">

#### grid-area

Gives an item a name so that it can be referenced by a template created with the `grid-template-areas` property. Alternatively, this property can be used as an even shorter shorthand for `grid-row-start` + `grid-column-start` + `grid-row-end` + `grid-column-end`.

Values:

- **`<name>`** - a name of your choosing
- **`<row-start>`/ `<column-start>` / `<row-end>` / `<column-end>`** - can be numbers or named lines

```css
.item {
    grid-area: <name> | <row-start> / <column-start> / <row-end> / <column-end>;
}
```

Examples:

As a way to assign a name to the item:

```css
.item-d {
    grid-area: header
}
```

As the short-shorthand for `grid-row-start` + `grid-column-start` + `grid-row-end` + `grid-column-end`:

```css
.item-d {
    grid-area: 1 / col4-start / last-line / 6
}
```

![Example of grid-area](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-start-end-d.png)

</div>

<div id="prop-justify-self">

#### justify-self

Aligns the content inside a grid item along the _row_ axis (as opposed to `align-self` which aligns along the _column_ axis). This value applies to the content inside a single grid item.

Values:

- **start** - aligns the content to the left end of the grid area
- **end** - aligns the content to the right end of the grid area
- **center** - aligns the content in the center of the grid area
- **stretch** - fills the whole width of the grid area (this is the default)

```css
.item {
    justify-self: start | end | center | stretch;
}
```

Examples:

```css
.item-a {
    justify-self: start;
}
```

![Example of justify-self set to start](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-justify-self-start.png)

```css
.item-a {
    justify-self: end;
}
```

![Example of justify-self set to end](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-justify-self-end.png)

```css
.item-a {
    justify-self: center;
}
```

![Example of justify-self set to center](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-justify-self-center.png)

```css
.item-a {
    justify-self: stretch;
}
```

![Example of justify-self set to stretch](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-justify-self-stretch.png)

To set alignment for _all_ the items in a grid, this behavior can also be set on the grid container via the `justify-items` property.

</div>

<div id="prop-align-self">

#### align-self

Aligns the content inside a grid item along the _column_ axis (as opposed to `justify-self` which aligns along the _row_ axis). This value applies to the content inside a single grid item.

Values:

- **start** - aligns the content to the top of the grid area
- **end** - aligns the content to the bottom of the grid area
- **center** - aligns the content in the center of the grid area
- **stretch** - fills the whole height of the grid area (this is the default)

```css
.item {
    align-self: start | end | center | stretch;
}
```

Examples:

```css
.item-a {
    align-self: start;
}
```

![Example of align-self set to start](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-align-self-start.png)

```css
.item-a {
    align-self: end;
}
```

![Example of align-self set to end](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-align-self-end.png)

```css
.item-a {
    align-self: center;
}
```

![Example of align-self set to center](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-align-self-center.png)

```css
.item-a {
    align-self: stretch;
}
```

![Example of align-self set to stretch](https://cdn.css-tricks.com/wp-content/uploads/2016/03/grid-align-self-stretch.png)

To align _all_ the items in a grid, this behavior can also be set on the grid container via the `align-items` property.

</div>

</div>

This article was ported over from [Chris House's guide](http://chris.house/blog/a-complete-guide-css-grid-layout/), by Chris himself, who is keeping both up-to-date.
